Repository pedroespindula/easy_plp, pull requests merged in 2019-09, with the labels that each got.

#9 Adiciona exercicios básicos
  exercicios/dobro.csv
  exercicios/fizz-buzz.csv
  exercicios/hello-world.csv
  exercicios/maior-string.csv
  exercicios/ordena-array.csv
  exercicios/rot13.csv
Labels: exercises

#10 Cria ambiente para C
  .gitignore
  c/Makefile
  c/hello.c
  c/main.c
  c/main.h
Labels: C, configuration

#11 Adiciona header file de interface
  c/interface.h
Labels: C, enhancement

#13 Conserta header files
  c/hello.c
  c/interface.h
  c/main.c
  c/main.h
Labels: C, enhancement

#14 Adiciona arquivo util.c
  c/util.c
Labels: C, enhancement

#15 Adiciona métodos count_files e get_dir_files
  c/main.h
  c/util.c
Labels: C, enhancement

#22 Conserta csv de testes
  exercicios/dobro.csv
  exercicios/fizz-buzz.csv
  exercicios/hello-world.csv
  exercicios/maior-string.csv
  exercicios/ordena-array.csv
  exercicios/rot13.csv
Labels: C, exercises
